// src/lib/components/DonutChart.svelte
<script lang="ts">
	import type { Segment } from '$lib/types';

	let {
		segments,
		ownColorHex,
		ownOpacity = 1,
		radius
	}: { segments: Segment[]; ownColorHex: string; ownOpacity?: number; radius: number } = $props();

	const BASE_STROKE = 10;

	function polar(r: number, angleDeg: number) {
		const a = ((angleDeg - 90) * Math.PI) / 180;
		return { x: r * Math.cos(a), y: r * Math.sin(a) };
	}

	// Arc centered on the origin (0,0). Ported from the original describeArc.
	function describeArc(r: number, startAngle: number, endAngle: number): string {
		const start = polar(r, endAngle);
		const end = polar(r, startAngle);
		const largeArc = endAngle - startAngle <= 180 ? '0' : '1';
		return `M ${start.x} ${start.y} A ${r} ${r} 0 ${largeArc} 0 ${end.x} ${end.y}`;
	}

	const arcs = $derived.by(() => {
		const size = 360 / segments.length;
		return segments.map((seg, i) => ({
			d: describeArc(radius, i * size, (i + 1) * size),
			color: seg.colorHex,
			opacity: seg.opacity,
			width: BASE_STROKE + seg.count * 3
		}));
	});
</script>

{#if segments.length > 1}
	<circle r={radius} fill="white" stroke={segments[0].colorHex} stroke-width="1" stroke-opacity="0.35" />
	{#each arcs as arc, i (i)}
		<path d={arc.d} fill="none" stroke={arc.color} stroke-opacity={arc.opacity} stroke-width={arc.width} />
	{/each}
	<circle r={radius / 3} fill="white" stroke={ownColorHex} stroke-opacity={ownOpacity} stroke-width="2.5" />
{:else if segments.length === 1}
	<circle
		r={radius}
		fill="white"
		stroke={segments[0].colorHex}
		stroke-opacity={segments[0].opacity}
		stroke-width={BASE_STROKE}
	/>
	<circle r={radius / 3} fill="white" stroke={ownColorHex} stroke-opacity={ownOpacity} stroke-width="2.5" />
{:else}
	<circle r={radius} fill="white" stroke={ownColorHex} stroke-opacity={ownOpacity} stroke-width={BASE_STROKE} />
{/if}

// components/DonutChart.vue
<template>
  <svg v-if="(numSegments > 1)">
    <path 
      v-for="(segment, index) in segments" 
      :key="index"
      fill="transparent"
      :stroke="getHexColour(segment.colour)"
      :stroke-width="(20 * segment.count)"
      :d="describeArc(circleData.x, circleData.y, circleData.radius + (5 * segment.count), arcPoints[index][0], arcPoints[index][1])"
    ></path>
  </svg>
  <svg v-else>
    <circle 
      fill="transparent"
      :cx="circleData.x"
      :cy="circleData.y"
      :r="circleData.radius"
      :stroke="getHexColour(this.segments[0].colour)"
      :stroke-width="20"
    ></circle>
  </svg>
</template>

<script lang="ts">
import Vue from 'vue'
import { CircleData, Segment } from '~/belief-map.types'

export default Vue.extend({
  name: 'DonutChart',
  props: ['segments', 'circleData'],
  data() {
    return {
      numSegments: this.segments.length,
    }
  },
  computed: {
    svgSize() {
      const circleData = this.circleData as CircleData
      return circleData.x * 2
    },
    arcSize() {
      const size = 360 / this.segments.length
      return size
    },
    arcPoints() {
      let arcs = [] as [number, number][];
      for (let i = 0; i < this.segments.length; i++) {
        const start = i * this.arcSize
        arcs.push([start, start + this.arcSize])
      }
      return arcs
    }
  },
  methods: {
    getHexColour(name: string) {
      switch (name) {
        case 'green darken-3':
          return '#2E7D32'
        case 'blue darken-3': 
          return '#2979FF'
        case 'indigo darken-3': 
          return '#283593'
        case 'deep-purple darken-3': 
          return '#4527A0'
        case 'amber darken-3': 
          return '#FF8F00'
        case 'orange darken-3': 
          return '#EF6C00'
        case 'red darken-3': 
          return '#C62828'
        default:
          return '#FFFFFF'
      }
    },
    // CODE TAKEN FROM https://stackoverflow.com/questions/5736398/how-to-calculate-the-svg-path-for-an-arc-of-a-circle
    describeArc(x: number , y: number , radius: number , startAngle: number , endAngle: number) {
      const start = this.polarToCartesian(x, y, radius, endAngle);
      const end = this.polarToCartesian(x, y, radius, startAngle);

      const largeArcFlag = endAngle - startAngle <= 180 ? "0" : "1";

      const d = [
          "M", start.x, start.y, 
          "A", radius, radius, 0, largeArcFlag, 0, end.x, end.y
      ].join(" ");

      return d;       
    },
    polarToCartesian(centerX: number, centerY: number, radius: number, angleInDegrees: number) {
      const angleInRadians = (angleInDegrees - 90) * Math.PI / 180.0;

      return {
        x: centerX + (radius * Math.cos(angleInRadians)),
        y: centerY + (radius * Math.sin(angleInRadians))
      };
    },
    // END OF TAKEN CODE
  },
})
</script>
